name: "Check our best practices"
description: "Check against our team's best practices for pull requests"

inputs:
  token:
    description: "A GitHub token to add a label to the PR"
    required: true
  regex:
    description: "A custom regular expression for PR titles"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Python and depends
      run: |
        sudo apt install python3 python3-requests
      shell: bash

    - name: PR title complies
      run: python3 ${{ github.action_path }}/pr_best_practices.py --pr-title "${{ github.event.pull_request.title }}"
      shell: bash

    - name: PR description is not empty (blocking)
      run: |
        python3 ${{ github.action_path }}/pr_best_practices.py --pr-description "${{ github.event.pull_request.body }}"
      shell: bash

    - name: Add 'best practice' label on success
      if: success()
      run: python ${{ github.action_path }}/pr_best_practices.py --add-label --token "$TOKEN" --repository "${{ github.event.repository.full_name }}" --pr-number "${{ github.event.pull_request.number }}"
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
